const String supabaseUrl = 'https://adonyrqdzcslbtkjlsktp.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkb255cnFkemNzbGJ0a2psc2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMDY5OTcsImV4cCI6MjA3NTU4Mjk5N30.GlnZNczjfOERZHjAHU4-xqQSekVWRMcNTIj_JWwSmFQ';
